import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.MESIMA_PLAYWRIGHT));const server=http.createServer((req,res)=>res.end(fs.readFileSync('index.html')));await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.MESIMA_CHROME});const ctx=await browser.newContext({viewport:{width:412,height:915},hasTouch:true,isMobile:true});const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
try{
 await p.goto(`http://127.0.0.1:${server.address().port}`);const ids=await p.evaluate(()=>{Engine.stop();Store.setPref('syncEnabled',false);const a=Store.addTask({title:'A',kind:'long',mission:'army'}),b=Store.addTask({title:'B',kind:'long',mission:'army'}),c=Store.addTask({title:'C',parentId:a.id,mission:'army'}),d=Store.addTask({title:'D',parentId:a.id,mission:'army'});UI.section='tasks';UI.render();return [a.id,b.id,c.id,d.id];});
 const cdp=await ctx.newCDPSession(p);const from=await p.locator(`[data-sub="${ids[2]}"] .st2`).boundingBox(),to=await p.locator(`[data-sub="${ids[3]}"] .st2`).boundingBox();
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:from.x+30,y:from.y+10}]});await p.waitForTimeout(520);await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:to.x+30,y:to.y+10}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await p.evaluate(id=>Store.subtasksOf(id)[0].title,ids[0]),'D');console.log('PASS mobile touch long-press child reorder');
 await p.waitForTimeout(550);await p.evaluate(id=>window.__openTask(id),ids[2]);await p.locator('#mFoot').getByRole('button',{name:'ערוך משימה',exact:true}).click();await p.locator('details').filter({has:p.locator('[data-parent]')}).locator('summary').click();await p.locator(`[data-parent="${ids[1]}"]`).check();await p.locator('#mFoot').getByRole('button',{name:'שמור',exact:true}).click();assert.equal(await p.evaluate(id=>Store.children(id).length,ids[1]),1);assert.equal(await p.locator(`[data-sub="${ids[2]}"]`).count(),2);
 await p.reload();await p.evaluate(()=>{Engine.stop();UI.section='tasks';UI.render();});assert.equal(await p.locator(`[data-sub="${ids[2]}"]`).count(),2);console.log('PASS shared membership editor and reload');
 assert.deepEqual(errors,[]);
}finally{await browser.close();server.close();}
