import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.MESIMA_PLAYWRIGHT));
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync('index.html'));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,executablePath:process.env.MESIMA_CHROME}),ctx=await browser.newContext({viewport:{width:412,height:915},timezoneId:'Asia/Jerusalem'}),p=await ctx.newPage(),errors=[];
p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(6000);fs.mkdirSync('test-results',{recursive:true});
const foot=n=>p.locator('#mFoot').getByRole('button',{name:n,exact:true});
try{
 await p.clock.setFixedTime(new Date('2026-09-17T09:15:00+03:00'));await p.goto(`http://127.0.0.1:${server.address().port}`);await p.evaluate(()=>{Engine.stop();Store.setPref('syncEnabled',false);});
 const ids=await p.evaluate(()=>{
  const project=Store.addTask({title:'הכנה לצילום ראשון',kind:'long',mission:'free'}),event=Store.addEvent({title:'צילום ראשון',date:'2026-10-17',time:'09:00',end:'12:00'}),task=Store.addTask({title:'להכין Shot List',parentId:project.id,mission:'free'}),related=Store.addTask({title:'לבדוק מצלמה',mission:'free'}),place=Store.addPlace('גן שמואל',32.44,34.95,250);
  for(let i=1;i<=9;i++)Store.finishTask(Store.addTask({title:'פעולה שהושלמה '+i,mission:'free'}).id);UI.render();return {project:project.id,event:event.id,task:task.id,related:related.id,place:place.id};
 });
 assert.equal(await p.locator('.reflections').count(),0);
 await p.clock.setFixedTime(new Date('2026-09-17T18:00:00+03:00'));await p.evaluate(()=>UI.render());assert.equal(await p.locator('.reflection-head').count(),1);assert.equal(await p.locator('.reflection-items li').count(),0);await p.screenshot({path:'test-results/48-daily-collapsed.png'});
 await p.locator('.reflection-head').click();assert.equal(await p.locator('.reflection-items li').count(),9);const note=p.locator('[data-reflection-note="day"]');await note.fill('יום טוב — צילמתי ולמדתי.\nלזכור להביא מצלמה.');await p.evaluate(()=>{Store.setPref('vib',false);UI.render();});assert.match(await note.inputValue(),/להביא מצלמה/);assert.equal(await note.evaluate(e=>e===document.activeElement),true);
 await p.reload();await p.evaluate(()=>Engine.stop());await p.locator('.reflection-head').click();assert.match(await note.inputValue(),/להביא מצלמה/);await p.screenshot({path:'test-results/48-daily-expanded.png'});console.log('PASS 18:00 visibility, all completions, note persistence and focus during updates');
 await p.evaluate(()=>{document.activeElement?.blur();UI.selDate='2026-09-16';UI.render();});assert.equal(await p.locator('.reflection-head').count(),1);
 await p.evaluate(()=>{UI.selDate='2026-09-18';UI.render();});assert.equal(await p.locator('.reflections').count(),0);
 await p.clock.setFixedTime(new Date('2026-09-20T18:00:00+03:00'));await p.evaluate(()=>{UI.selDate='2026-09-20';UI.render();});assert.equal(await p.locator('.reflection-head').count(),2);await p.locator('[data-reflection-toggle="week:2026-09-13"]').click();assert.equal(await p.locator('.reflection-day').count(),7);assert.match(await p.locator('.reflection-day-note').innerText(),/למדתי/);await p.locator('[data-reflection-note="week"]').fill('השבוע התקדמתי בצילום');await p.locator('.reflection-head').first().click();assert.equal(await p.locator('.reflection-body').count(),2);await p.screenshot({path:'test-results/48-weekly.png'});console.log('PASS past/future visibility, weekly grouping and independent expansion');
 await p.evaluate(id=>{document.activeElement?.blur();Modal.shut();window.__openTask(id);},ids.project);await foot('ערוך משימה').click();await p.locator('#etEvPick').click();await p.locator(`[data-e="${ids.event}"]`).click();assert.match(await p.locator('#etProjectEvent').innerText(),/צילום ראשון/);await foot('שמור').click();assert.equal(await p.evaluate(id=>Store.task(id).planned,ids.project),null);
 await p.evaluate(id=>window.__openEvent(id),ids.event);assert.match(await p.locator(`[data-preparation="${ids.project}"]`).innerText(),/0 מתוך 1/);await p.locator('[data-preparation]').click();assert.equal(await p.locator('#mTitle').innerText(),'הכנה לצילום ראשון');await p.locator('[data-d="evopen"]').click();assert.equal(await p.locator('#mTitle').innerText(),'צילום ראשון');console.log('PASS linking project to event through real editor, progress and reverse navigation');
 await p.evaluate(id=>{Modal.shut();window.__openTask(id);},ids.task);await foot('ערוך משימה').click();assert.equal(await p.locator('#etRelatedMain').innerText(),'');assert.equal(await p.locator('[data-rel-manage]').isVisible(),false);await p.locator('#etAdvHead').click();await p.locator('[data-rel-manage]').click();await p.locator(`[data-rel-choice="${ids.related}"]`).check();await foot('בחר').click();assert.match(await p.locator('#etRelatedMain').innerText(),/לבדוק מצלמה/);assert.equal(await p.evaluate(id=>Store.relatedTasks(id).length,ids.task),0);await foot('שמור').click();assert.equal(await p.evaluate(id=>Store.relatedTasks(id).length,ids.task),1);
 await p.evaluate(id=>window.__openTask(id),ids.related);assert.match(await p.locator('[data-related-task]').innerText(),/Shot List/);await p.locator('[data-related-task]').click();assert.equal(await p.locator('#mTitle').innerText(),'להכין Shot List');console.log('PASS quiet unlinked UI, staged relationship changes and bidirectional details');
 await p.evaluate(()=>{Modal.shut();UI.screen='places';UI.render();});await p.locator('#placeQuery').fill('סופר־פארם');await p.locator('#placeManual').click();await p.locator('#manualPlaceParent').selectOption(ids.place);await foot('שמור').click();const manual=await p.evaluate(()=>Store.all.places.find(p=>p.name==='סופר־פארם'));assert.equal(manual.parentId,ids.place);assert.equal(manual.lat,null);await p.locator(`[data-place-edit="${manual.id}"]`).click();assert.equal(await p.locator('#manualPlaceName').inputValue(),'סופר־פארם');await foot('ביטול').click();console.log('PASS manual sublocation creation and editing without coordinates');
 await p.setViewportSize({width:1920,height:1080});await p.evaluate(()=>{document.documentElement.classList.add('desktop');UI.screen=null;UI.section='today';UI.selDate='2026-09-17';UI.render();});await p.screenshot({path:'test-results/48-desktop.png'});assert.deepEqual(errors,[]);console.log('PASS no JavaScript errors, mobile and desktop screenshots');
}finally{await browser.close();server.close();}
