import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.MESIMA_PLAYWRIGHT));
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync('index.html'));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,executablePath:process.env.MESIMA_CHROME});const ctx=await browser.newContext({viewport:{width:1100,height:850}});const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(7000);fs.mkdirSync('test-results',{recursive:true});
try{
 await p.goto(`http://127.0.0.1:${server.address().port}`);await p.evaluate(()=>{Engine.stop();Store.setPref('syncEnabled',false);});
 const ids=await p.evaluate(()=>{const a=Store.addTask({title:'פרויקט צילום',note:'תיאור',kind:'long',mission:'army'}),b=Store.addTask({title:'פרויקט שני',kind:'long',mission:'army'});const kids=[];for(let i=1;i<=7;i++)kids.push(Store.addTask({title:'משימה '+i,note:'תיאור '+i,parentId:a.id,mission:'army'}).id);UI.section='tasks';UI.render();return {a:a.id,b:b.id,kids};});
 const card=()=>p.locator(`.tcard[data-id="${ids.a}"]`);
 assert.equal(await p.locator('.drag-handle').count(),0);assert.equal(await card().locator('.tsub').count(),4);
 await card().locator('[data-act="childrenToggle"]').click();assert.equal(await card().locator('.tsub').count(),7);assert.equal(await p.locator('#modal.on').count(),0);
 await card().locator('[data-act="childrenToggle"]').click();assert.equal(await card().locator('.tsub').count(),4);console.log('PASS inline expansion/collapse and no drag icons');
 const before=await p.evaluate(()=>Store.allRoots().map(t=>t.id)),from=p.locator(`.tcard[data-id="${ids.b}"] [data-act="detail"]`),to=card().locator('[data-act="detail"]');
 let a=await from.boundingBox(),b=await to.boundingBox();await p.mouse.move(a.x+100,a.y+12);await p.mouse.down();await p.mouse.move(b.x+100,b.y+12,{steps:5});await p.mouse.up();assert.deepEqual(await p.evaluate(()=>Store.allRoots().map(t=>t.id)),before);await p.evaluate(()=>Modal.shut());
 a=await from.boundingBox();b=await to.boundingBox();await p.mouse.move(a.x+100,a.y+12);await p.mouse.down();await p.waitForTimeout(550);await p.mouse.move(b.x+100,b.y+12,{steps:8});await p.mouse.up();assert.deepEqual(await p.evaluate(()=>Store.allRoots().map(t=>t.id)),before.reverse());console.log('PASS long-press reorder and quick-gesture protection');
 await p.evaluate(()=>{UI.selDate=Plan.shift(Plan.today(),5);UI.section='today';UI.render();});await p.locator('#tvModes [data-v="day"]').click();assert.equal(await p.evaluate(()=>UI.selDate),await p.evaluate(()=>Plan.today()));console.log('PASS Today resets selected date');
 const habit=await p.evaluate(()=>Store.addTask({title:'תפילת הדרך',note:'הברכה המלאה לצורך בדיקה',mission:'free',repeat:{days:[0,1,2,3,4,5,6],times:['23:58','23:59']}}).id);
 await p.evaluate(id=>window.__alarm('h_'+id+'_'+Plan.today()+'@23:58'),habit);await p.locator('#alert.on').waitFor();assert.match(await p.locator('#alDet').innerText(),/הברכה המלאה/);await p.locator('#alComplete').click();assert.equal(await p.evaluate(id=>Store.habitFull(Store.task(id),Plan.today()),habit),true);console.log('PASS notification description routing and completion');
 await p.evaluate(()=>{UI.screen='places';UI.render();});
 await p.route('https://nominatim.openstreetmap.org/**',async r=>{await new Promise(res=>setTimeout(res,500));await r.fulfill({json:[{name:'חנות בדיקה',display_name:'חנות בדיקה, חיפה',lat:'32.81',lon:'34.99'}]});});await p.route('https://photon.komoot.io/**',r=>r.fulfill({json:{features:[]}}));await p.route('https://overpass-api.de/**',r=>r.fulfill({json:{elements:[]}}));
 await p.locator('#placeQuery').fill('חנות בדיקה');await p.locator('#placeFind').click();await p.evaluate(()=>{UI.render();Store.setPref('vib',false);});assert.equal(await p.locator('#placeQuery').inputValue(),'חנות בדיקה');await p.locator('[data-result="0"]').click();await p.locator('#mFoot').getByRole('button',{name:'שמור מקום',exact:true}).click();assert.equal(await p.evaluate(()=>Store.all.places.some(x=>x.name==='חנות בדיקה')),true);console.log('PASS search survives updates and saves selected coordinates');
 await p.setViewportSize({width:1920,height:1080});await p.evaluate(()=>{document.documentElement.classList.add('desktop');UI.screen=null;UI.section='tasks';UI.render();});const bounds=await p.locator('#app').boundingBox();assert.equal(bounds.x,0);assert.equal(bounds.width,1920);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),1920);await p.screenshot({path:'test-results/desktop-47.png'});assert.deepEqual(errors,[]);console.log('PASS full-width desktop and no JavaScript errors');
}finally{await browser.close();server.close();}
